### ISSUE TITLE
Homebridge crashes with version 3.0.0

### ISSUE THREAD

**Issue by BigKrisch** [OpenWonderLabs/homebridge-switchbot-openapi#103]
Describe The Bug:

since version 3.0.0 I always get the following error message with the curtains and the Homebridge crashes:

`[13.2.2021, 00:07:23] TypeError: this.doCurtainUpdate.push is not a function
    at Curtain.handleTargetPositionSet (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/devices/curtains.ts:286:26)
    at Characteristic.emit (events.js:315:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1461:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1303:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
`
With version 2.4.0 everything still works fine.

To Reproduce:

Open or close the curtains from HomeKit

Homebridge Config:

`{

            "name": "SwitchBot",
            "credentials": {
                "openToken": "xxxxxxxxxxxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 120,
                "pushRate": 2,
                "hide_device": [
                    "DDBEE08B89AB"
                ],
                "bot": {
                    "device_press": [
                        "F2A3DD9D8018"
                    ]
                },
                "curtain": {
                    "set_minStep": 1,
                    "set_min": 0,
                    "set_max": 100
                }
            },
            "devicediscovery": false,
            "platform": "SwitchBot"
        } `

Environment:

Node.js Version: 14.15.5
NPM Version: 7.5.4
Homebridge Version: 1.2.5
Homebridge SwitchBot Plugin Version: 3.0.0
Homebridge Config UI X Plugin Version: 4.38.0
Operating System: Raspbian

**Comment by donavanbecker** [comment]
@BigKrisch To much of the template was changed. That's what it closed. In the future if you just add in your info you should be good. Sorry about that.

I will look into this.

**Comment by donavanbecker** [comment]
@BigKrisch Can you try the latest beta of homebridge?

**Comment by BigKrisch** [comment]
@donavanbecker I will follow the template better next time. Thank you for reopening.

With the current Homebridge version 1.3.0-beta.56 I get this error message:

`[13.2.2021, 00:55:10] Received warning for the plugin 'homebridge-switchbot-openapi' from the characteristic 'Target Position': Unhandled error thrown inside write handler for characteristic: TypeError: this.doCurtainUpdate.push is not a function
    at Curtain.handleTargetPositionSet (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/devices/curtains.ts:286:26)
    at Characteristic.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1588:16
    at new Promise (<anonymous>)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1586:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16) `

**Comment by donavanbecker** [comment]
@BigKrisch I found the issue. I will get a fix out soon.

**Comment by BigKrisch** [comment]
Perfect. Thank you very much!

**Comment by donavanbecker** [comment]
Version 3.0.1 fixes issue.
