### ISSUE TITLE
Bot devices stopped working after upgrade to v3.3.0

### ISSUE THREAD

**Issue by idoshimoni** [OpenWonderLabs/homebridge-switchbot-openapi#128]
After upgrade to latest build, my bot devices stopped working

[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] {"statusCode":100,"body":{"deviceList":[{"deviceId":"D089A918E2B8","deviceName":"Living Room Hub Plus","deviceType":"Hub Plus","hubDeviceId":"000000000000"},{"deviceId":"D5109803D561","deviceName":"Intercom Bot","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"D089A918E2B8"},{"deviceId":"E87E4D816216","deviceName":"Suction Bot","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"D089A918E2B8"}],"infraredRemoteList":[]},"message":"success"}
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] Total SwitchBot Devices Found: 3
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] Total IR Devices Found: 0
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] {"deviceId":"D089A918E2B8","deviceName":"Living Room Hub Plus","deviceType":"Hub Plus","hubDeviceId":"000000000000"}
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] Discovered a Hub Plus
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] {"deviceId":"D5109803D561","deviceName":"Intercom Bot","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"D089A918E2B8"}
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] Discovered Intercom Bot Bot
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] Restoring existing accessory from cache: Intercom Bot Bot DeviceID: D5109803D561
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] {"deviceId":"E87E4D816216","deviceName":"Suction Bot","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"D089A918E2B8"}
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] Discovered Suction Bot Bot
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] Restoring existing accessory from cache: Suction Bot Bot DeviceID: E87E4D816216
(node:92450) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
    at new Bot (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/devices/bots.ts:78:8)
    at SwitchBotPlatform.createBot (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:439:9)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:237:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:92450) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:92450) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:92450) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
    at new Bot (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/devices/bots.ts:78:8)
    at SwitchBotPlatform.createBot (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:439:9)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:237:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:92450) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2/24/2021, 10:42:26 PM] [idoshimoni@gmail.com] deviceStatus - Living Room Hub Plus {"statusCode":100,"body":{},"message":"success"}
[2/24/2021, 10:42:27 PM] [idoshimoni@gmail.com] deviceStatus - Intercom Bot {"statusCode":100,"body":{"deviceId":"D5109803D561","deviceType":"Bot","hubDeviceId":"D089A918E2B8","power":"on"},"message":"success"}
[2/24/2021, 10:42:27 PM] [idoshimoni@gmail.com] deviceStatus - Suction Bot {"statusCode":100,"body":{"deviceId":"E87E4D816216","deviceType":"Bot","hubDeviceId":"D089A918E2B8","power":"on"},"message":"success"}
[2/24/2021, 10:42:28 PM] [Homebridge UI] Homebridge Config UI X v4.39.0 is listening on :: port 8080
[2/24/2021, 10:43:45 PM] [Roborock] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
[2/24/2021, 10:43:45 PM] [Roborock] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 100%
[2/24/2021, 10:43:45 PM] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 104 over miIO. Converting to HomeKit
[2/24/2021, 10:43:45 PM] [Roborock] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 104 over miIO "Max" > HomeKit speed 100%
[2/24/2021, 10:43:46 PM] [Roborock] INF getPauseState | roborock.vacuum.s5 | Pause possible is false

**Comment by donavanbecker** [comment]
@idoshimoni You need to update to homebridge v1.3.0
