### ISSUE TITLE
Curtains Have Disappeared

### ISSUE THREAD

**Issue by jdegnan-ghub** [OpenWonderLabs/homebridge-switchbot-openapi#130]
After being unresponsive after a few days, I went in to check status of curtains in homebridge. Though they were initially still there (and continued to be unresponsive) I then began to troubleshoot. When I tied upgrading the plugin, the curtains then totally disappeared.

Curtains no longer appearing as accessories despite being recognized by the plugin in the log.

Curtains had been working normally up until a few days ago. No ability to reproduce working curtains

**Homebridge Logs:**
[homebridge.log.txt](https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/files/6039758/homebridge.log.txt)

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 189C",
        "username": "0E:9A:C5:E4:8D:54",
        "port": 51718,
        "pin": "181-55-470"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "REDACTED",
                "notice": "Keep your token a secret!"
            },
            "devicediscovery": true,
            "platform": "SwitchBot"
        }
    ],
    "disabledPlugins": [
        "homebridge-tplink-smarthome",
        "homebridge-harmony"
    ]
}
```

**Screenshots:**

**Device Model:**

Raspberry Pi 4 Model B Rev 1.2

# **Environment:**

- **Node.js Version**: v14.15.5
- **NPM Version**: v6.14.11
- **Homebridge Version**: v1.3.1
- **Homebridge SwitchBot Plugin Version**: v3.3.3
- **Homebridge Config UI X Plugin Version**: v4.39.0
- **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
Can you please fill out the full template? Need more info to troubleshoot.

**Comment by jonzhan** [comment]
I also had a similar issue (curtains not responding) after updating to v3.0.0 and Homebridge v1.3.1 - for me it was fixed by adding

```
"curtain": {
  "refreshRate": 5
}
```

I don't remember the log message (and it is gone now), but it indicated that refreshRate was undefined or something similar.

I did **not** experience the same issue of the curtains not appearing as accessories, however.

**Comment by jeroen020** [comment]
I seem to have the same/similar issue since yesterday, when I (also) did a couple of updates to my Homebridge and the plugin. My curtains were no longer responding. 
Strangely, I also get Switchbot-related errors in the log after a restart under another plugin (p1):

`[25/02/2021, 09:13:13] [P1] error: unhandled rejection: TypeError: Cannot read property 'refreshRate' of undefined
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/devices/curtains.ts:104:53)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:594:7)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:253:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[25/02/2021, 09:13:13] [P1] error: unhandled rejection: TypeError: Cannot read property 'refreshRate' of undefined
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/devices/curtains.ts:104:53)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:594:7)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:253:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[25/02/2021, 09:13:13] [P1] error: unhandled rejection: TypeError: Cannot read property 'refreshRate' of undefined
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/devices/curtains.ts:104:53)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:594:7)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:253:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

The error disappears when I disable or remove the Switchbot plugin. When I reinstall the Switchbot plugin the error returns, but now my curtains no longer show up in the Accessories tab in Homebridge UI nor in Homekit.

**Comment by donavanbecker** [comment]
v3.3.2 should correct this. can all validate this?

**Comment by jonzhan** [comment]
Updated to v3.3.2 and removed manual `refreshRate` setting, with this result

```
(node:17160) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'refreshRate' of undefined
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/devices/curtains.ts:104:53)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:562:9)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:253:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Works again after providing `refreshRate`!

**Comment by jeroen020** [comment]
Updated to 3.3.2 and restarted but still get this error 3 times (I have 3 curtains), logged under the [P1] plugin instead of the [SwitchBot] one:
`[25/02/2021, 12:18:32] [P1] error: unhandled rejection: TypeError: Cannot read property 'refreshRate' of undefined
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/devices/curtains.ts:104:53)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:594:7)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:253:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`
I tried setting the overall refreshRate in the config to 300 but the issue remains.
I then added "refreshRate": 5 to the curtain section in the config and now the error is gone, the curtains work and are added to HomeKit (as new rollerblinkds in the default room, so I'll have to redo my automations...)

**Comment by jdegnan-ghub** [comment]
Same - updated to 3.2.2. Still no curtains showing up.

**Comment by donavanbecker** [comment]
I need everyone to create their own issues and @jdegnan-ghub I need you to fill out the full issue template. Without know versions of plugin, homebridge, etc. I can't troubleshoot as well.

**Comment by jonzhan** [comment]
> I need everyone to create their own issues and @jdegnan-ghub I need you to fill out the full issue template. Without know versions of plugin, homebridge, etc. I can't troubleshoot as well.

Sorry if this is widely known - still not familiar with protocol. What is best for you? Do we fill out the issue template in a comment in this issue or in fresh duplicate issues? :)

**Comment by donavanbecker** [comment]
if v3.3.3. doesn't work then everyone needs to do rest new tissues and fill it out completely so I can know their setup info.

**Comment by jdegnan-ghub** [comment]
> I need everyone to create their own issues and @jdegnan-ghub I need you to fill out the full issue template. Without know versions of plugin, homebridge, etc. I can't troubleshoot as well.

Done.

**Comment by donavanbecker** [comment]
@jdegnan-ghub Thanks!! Are you getting the same logs as before?

**Comment by donavanbecker** [comment]
@jdegnan-ghub can you try the new beta? 

Beta: `v3.3.4-beta.0`

**Comment by jdegnan-ghub** [comment]
> @jdegnan-ghub can you try the new beta?
> 
> Beta: `v3.3.4-beta.0`

yup! that fixed it! thank you!!!

**Comment by donavanbecker** [comment]
@jdegnan-ghub Awesome! Also I would recommend setting your plugins up as child bridges so you can isolate your issues. I saw a lot of issues with the tp-link plugin, which can cause issues with other plugins.

**Comment by jonzhan** [comment]
Thanks for this fix! :)
