### ISSUE TITLE
TypeError: this.service.getCharacteristic(...).setProps(...).onGet is not a function

### ISSUE THREAD

**Issue by willliamchan** [OpenWonderLabs/homebridge-switchbot-openapi#136]
Error loading the plug-in since 3.3.1, same error with 3.3.2

25/02/2021, 20:02:17 [SwitchBot] Total SwitchBot Devices Found: 8
25/02/2021, 20:02:17 [SwitchBot] Total IR Devices Found: 0
25/02/2021, 20:02:17 [SwitchBot] Adding new accessory: Curtain Black Curtain DeviceID: C68AC659F332
25/02/2021, 20:02:17 [SwitchBot] Main Curtain: Curtain Black, DeviceID: C68AC659F332
25/02/2021, 20:02:17 [SwitchBot] Adding new accessory: TGC Bot DeviceID: CD2648945093
25/02/2021, 20:02:17 [SwitchBot] Adding new accessory: Curtain White Curtain DeviceID: D95E941BA0EB
25/02/2021, 20:02:17 [SwitchBot] Main Curtain: Curtain White, DeviceID: D95E941BA0EB
25/02/2021, 20:02:17 TypeError: this.service.getCharacteristic(...).setProps(...).onGet is not a function
    at new Curtain (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:54:14)
    at SwitchBotPlatform.createCurtain (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:515:13)
    at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:227:30)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
25/02/2021, 20:02:17 TypeError: this.service.getCharacteristic(...).onSet is not a function
    at new Bot (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/devices/bots.js:58:14)
    at SwitchBotPlatform.createBot (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:412:13)
    at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:215:30)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
25/02/2021, 20:02:17 TypeError: this.service.getCharacteristic(...).setProps(...).onGet is not a function
    at new Curtain (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:54:14)
    at SwitchBotPlatform.createCurtain (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:515:13)
    at SwitchBotPlatform.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-switchbot-openapi/dist/platform.js:227:30)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

Install 3.3.1, fill-in the token and it will show up the error.

**Logs:**

```
Show the Homebridge logs here. If using Homebridge Config-UI-X, you can easly downlaod your log by visiting the log page on the UI and Clicking the Download Icon in the top right.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.

There is a hidden `"devicediscovery: true"` option that you can add to your config that will output data about your device to your log also.

***Read and Paste over this Text the Text Above^^^^^^
```

**Homebridge Config:**

```json
Paste your homebridge config.json here.
Remove any sensitive information, such as your homebridge-switchbot-openapi token.

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

**Device Model:**

# **Environment:**

- **Node.js Version**: 
- **NPM Version**: 
- **Homebridge Version**: 
- **Homebridge SwitchBot Plugin Version**:
- **Homebridge Config UI X Plugin Version**:
- **Operating System**:

**Comment by willliamchan** [comment]
Not sure what is happening and I had the plug-in uninstalled to allow hoobs back to normal.

**Comment by donavanbecker** [comment]
@willliamchan You need to have homebridge v1.3.1 installed as the changelogs says.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).
