### ISSUE TITLE
SwitchBot API / Token Problem -  Causes Homebridge Crash

### ISSUE THREAD

**Issue by DJay-X** [OpenWonderLabs/homebridge-switchbot-openapi#19]
@donavanbecker @SwitchBot-Wonderlabs 

Crash of entire homebridge because of SwitchBot API / Token Problem?
Not depending on v1.0.1 or v1.0.2-beta.3.

If something like this happens, probably the Plugin shouldn't crash the entire Homebridge in the future.
[28.12.2020, 14:42:24] Got SIGTERM, shutting down Homebridge...

Unfortunately I had to completely remove SwitchBot form the config.json for now because of this issue.

I hope the attached log helps, to get everything up and running again fast. 

Thanks
```
Error: Request failed with status code 401
    at createError (/usr/local/lib/node_modules/homebridge-switchbot-openapi/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-switchbot-openapi/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-switchbot-openapi/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
 {
  config: {
    url: 'https://api.switch-bot.com/v1.0/devices',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization: 'xxxxxxxxx',
      'Content-Type': 'application/json; charset=utf8',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'json',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.switch-bot.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.switch-bot.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 56,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /v1.0/devices HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Authorization: xxxxxxxxx\r\n' +
      'Content-Type: application/json; charset=utf8\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Host: api.switch-bot.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 5,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/v1.0/devices',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 401,
      statusMessage: 'Unauthorized',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.switch-bot.com/v1.0/devices',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.switch-bot.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.switch-bot.com/v1.0/devices',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      authorization: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      date: 'Mon, 28 Dec 2020 14:13:27 GMT',
      'content-type': 'application/json',
      'content-length': '26',
      connection: 'close',
      'x-amzn-requestid': 'xxxxxxxxx',
      'x-amzn-errortype': 'UnauthorizedException',
      'x-amz-apigw-id': 'xxxxxxxxx='
    },
    config: {
      url: 'https://api.switch-bot.com/v1.0/devices',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'json',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /v1.0/devices HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: xxxxxxxxx\r\n' +
        'Content-Type: application/json; charset=utf8\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: api.switch-bot.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1.0/devices',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.switch-bot.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { message: 'Unauthorized' }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
Error: Request failed with status code 401
    at createError (/usr/local/lib/node_modules/homebridge-switchbot-openapi/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-switchbot-openapi/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-switchbot-openapi/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
 {
  config: {
    url: 'https://api.switch-bot.com/v1.0/devices',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization: 'xxxxxxxxx',
      'Content-Type': 'application/json; charset=utf8',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'json',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.switch-bot.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.switch-bot.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 56,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /v1.0/devices HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Authorization: xxxxxxxxx\r\n' +
      'Content-Type: application/json; charset=utf8\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Host: api.switch-bot.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 5,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/v1.0/devices',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 401,
      statusMessage: 'Unauthorized',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.switch-bot.com/v1.0/devices',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.switch-bot.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.switch-bot.com/v1.0/devices',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      authorization: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      date: 'Mon, 28 Dec 2020 14:13:27 GMT',
      'content-type': 'application/json',
      'content-length': '26',
      connection: 'close',
      'x-amzn-requestid': 'xxxxxxxxx',
      'x-amzn-errortype': 'UnauthorizedException',
      'x-amz-apigw-id': 'xxxxxxxxx='
    },
    config: {
      url: 'https://api.switch-bot.com/v1.0/devices',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'json',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /v1.0/devices HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: xxxxxxxxx\r\n' +
        'Content-Type: application/json; charset=utf8\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: api.switch-bot.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1.0/devices',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.switch-bot.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { message: 'Unauthorized' }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by DJay-X** [comment]
@donavanbecker That is too strict I think. 🤷🏼‍♂️

**Comment by donavanbecker** [comment]
@DJay-X the issue validate looks at the issue templates if they are not followed then it automatically closes the issue. I know you skipped it since I don't see specific text that the templates follow. but no big deal I can just reopen it. The templates are good because it asks for more info than what is usually provided.

**Comment by donavanbecker** [comment]
@DJay-X do you have an example or extra log of when this happened. I understand the error, but to have more context will help fix this.

**Comment by DJay-X** [comment]
Out of the blue, the crash with the attached errors occurred. Homebridge not working at all and running in a "trying to start again" loop.
I changed nothing. Token is the same as from the beginning.
I rebooted Homebridge several times but that didn't fix the problem. It always ends after the errors with "Got SIGTERM, shutting down Homebridge..."
Going back to v1.0.1 didn't help. v1.0.2-beta.3 neither.
Unfortunately I had to completely remove SwitchBot form the config.json for now because of this issue and getting homebridge back to start again.

**Comment by donavanbecker** [comment]
@DJay-X, I haven't ran into this at all. Can you post your switchbot config when it was in homebridge?

**Comment by DJay-X** [comment]
Well the config is nothing special and not a lot to change. It also as of course not changed the last days.

   {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "xxxxxxxx",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot"
        }

**Comment by donavanbecker** [comment]
@DJay-X and if you add this back in you get the same error?

**Comment by DJay-X** [comment]
I already updated.
However, now Homebridge does not crash anymore, but the Plugin is not discovering anything anymore like before. 

[28.12.2020, 17:33:21] Loaded plugin: homebridge-switchbot-openapi@1.0.2-beta.4
[28.12.2020, 17:33:21] Registering platform 'homebridge-switchbot-openapi.SwitchBot'
[28.12.2020, 17:33:21] [SwitchBot] Initializing SwitchBot platform...
[28.12.2020, 17:33:21] [SwitchBot] Using Default Refresh Rate.
[28.12.2020, 17:33:23] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"

**Comment by donavanbecker** [comment]
@DJay-X yeah not sure. I posted another beta that should catch even more errors.

**Comment by DJay-X** [comment]
Thanks a lot @donavanbecker 

But unfortunately I don't see anything additional.

```
[28.12.2020, 18:00:19] Loaded plugin: homebridge-switchbot-openapi@1.0.2-beta.5
[28.12.2020, 18:00:19] Registering platform 'homebridge-switchbot-openapi.SwitchBot'
[28.12.2020, 18:00:19] [SwitchBot] Initializing SwitchBot platform...
[28.12.2020, 18:00:19] [SwitchBot] Using Default Refresh Rate.
[28.12.2020, 18:00:21] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"
```

I also unplugged and re-plugged the Hub mini, restarted homebridge again but that didn't change anything.
No devices are discovered anymore. 🤷🏼‍♂️

**Comment by donavanbecker** [comment]
> Thanks a lot @donavanbecker
> 
> But unfortunately I don't see anything additional.
> 
> ```
> [28.12.2020, 18:00:19] Loaded plugin: homebridge-switchbot-openapi@1.0.2-beta.5
> [28.12.2020, 18:00:19] Registering platform 'homebridge-switchbot-openapi.SwitchBot'
> [28.12.2020, 18:00:19] [SwitchBot] Initializing SwitchBot platform...
> [28.12.2020, 18:00:19] [SwitchBot] Using Default Refresh Rate.
> [28.12.2020, 18:00:21] [SwitchBot] Failed to Discover Devices. "Request failed with status code 401"
> ```
> 
> I also unplugged and re-plugged the Hub mini, restarted homebridge again but that didn't change anything.
> No devices are discovered anymore. 🤷🏼‍♂️

I would open up a ticket through the SwitchBot app, letting them know it looks like your token not longer works. 

FYI, I am not having this issue.

**Comment by DJay-X** [comment]
Yesterday I opened a Ticket for SwitchBot an I pointed to the - probably - Token issue and this conversation. 
I have no reply yet. But this morning I installed @1.0.2-beta.8 and restarted homebridge.
Now the devices are discovered again. Hopefully this will not happen again when we are out of beta. 😅


```
[29.12.2020, 08:17:34] Loaded plugin: homebridge-switchbot-openapi@1.0.2-beta.8
[29.12.2020, 08:17:34] Registering platform 'homebridge-switchbot-openapi.SwitchBot'
[29.12.2020, 08:17:35] [SwitchBot] Initializing SwitchBot platform...
[29.12.2020, 08:17:35] [SwitchBot] Using Default Refresh Rate.
[29.12.2020, 08:17:37] [SwitchBot] Total Devices Found: 10
[29.12.2020, 08:17:37] [SwitchBot] Discovered Luftbefeuchter Humidifier
[29.12.2020, 08:17:37] [SwitchBot] Discovered Living Room Curtain left Curtain
[29.12.2020, 08:17:37] [SwitchBot] A SwitchBot Device has been discovered with Device Type: Bot, which is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
[29.12.2020, 08:17:37] [SwitchBot] A SwitchBot Device has been discovered with Device Type: Bot, which is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
[29.12.2020, 08:17:37] [SwitchBot] A SwitchBot Device has been discovered with Device Type: Bot, which is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
[29.12.2020, 08:17:37] [SwitchBot] A SwitchBot Device has been discovered with Device Type: Bot, which is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
[29.12.2020, 08:17:37] [SwitchBot] A SwitchBot Device has been discovered with Device Type: Remote, which is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
[29.12.2020, 08:17:37] [SwitchBot] A SwitchBot Device has been discovered with Device Type: Hub Mini, which is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
[29.12.2020, 08:17:37] [SwitchBot] A SwitchBot Device has been discovered with Device Type: Bot, which is currently not supported. Submit Feature Requests Here: https://git.io/JL14Z
[29.12.2020, 08:17:37] [SwitchBot] Discovered Living Room Curtain right Curtain
```

**Comment by donavanbecker** [comment]
Error 401 is caused by too many requests from v1.0.2 beta.3.

**Comment by DJay-X** [comment]
@donavanbecker @SwitchBot-Wonderlabs I don't know what to do now.

The log is looking okay now as above, but there are no devices showing up at all in the Home / Eve App.

I deleted the config.json part, deinstalled the plugin, restart homebridge.
Installed the Plugin v1.0.2 beta.8 and the config part. Restarted homebridge again.

But still there is no device showing up. Not the humidifier, not the 2x curtain bots. 

I hope you have an idea? Thanks in advance.

**Comment by donavanbecker** [comment]
@DJay-X Are you using Homebridge UI?

**Comment by DJay-X** [comment]
> Are you using Homebridge UI?

I do. 

OS | Raspbian GNU/Linux Stretch (9)
raspberrypi-3BPlus
192.168.178.111
Node v14.15.3
Npm v6.14.10
homebridge v1.2.5
Config UI X v4.36.0
/var/lib/homebridge-2nd-instance
/var/lib/homebridge-2nd-instance/config.json



> Are you using Homebridge UI?
> If so I would go into the homebridge settings, and I would look at the cached accessories there. There is an option to reset cache on a single accessory or on all accessories. I would look at the single accessories one and see if your SwitchBot devices are in there, if so I would delete cache only on those accessories.

I already did yesterday and now again. But there are also no SwitchBot Devices. 
After I checked I manually deleted cachedAccessories File yesterday, also without any success.

It is strange. Every other Plugin and Device is working as before perfectly. And you remember, when starting with your plugin everything was okay also.

I have no Idea how to fix this and wehere the problem is. I'm a bit lost now. 🥺

**Comment by donavanbecker** [comment]
@DJay-X Are you on the homebridge discord server?

**Comment by DJay-X** [comment]
> @DJay-X Are you on the homebridge discord server?

I'm DJay#8716 but never used it. 😅 Not very familiar with it. But we can try.

**Comment by donavanbecker** [comment]
@DJay-X Good to close?
