### ISSUE TITLE
SwitchBot Hub Mini Support

### ISSUE THREAD

**Issue by donavanbecker** [OpenWonderLabs/homebridge-switchbot-openapi#9]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Support for SwitchBot Hub Mini.

**Describe alternatives you've considered**

Displayed as IR Devices in HomeKit.

**Additional context**

None.

**Comment by Kohle81** [comment]
Where can I find the config for the manual installation of this plugin for the Hub mini?

**Comment by donavanbecker** [comment]
@Kohle81 We are working on adding support. Once support is added, I can reach back out on this issue.

**Comment by Kohle81** [comment]
Thanks for your answer. Great!

**Comment by DJay-X** [comment]
@donavanbecker @SwitchBot-Wonderlabs 

I received my Token and started with the Plugin.
However, not any device is showing up in HomeKit. Not sure where to start.
A lot of "undefined" in the log.

Mostly I would love to have my SwitchBot Curtain and SwitchBot Bot to work.
Humidifier is a nice add-on later but not so important at the moment.

Please guide me in the right direction how I can help with more information.

Thanks again.

![Napkin 24 12 20, 11 44 26 AM](https://user-images.githubusercontent.com/3874239/103083715-646ebd00-45dd-11eb-83f3-cf2b8e623e82.png)



```
[24.12.2020, 11:24:25] Loaded plugin: homebridge-switchbot-openapi@0.1.0
[24.12.2020, 11:24:25] Registering platform 'homebridge-switchbot-openapi.Switch-Bot'
[24.12.2020, 11:24:25] [Switch-Bot] Initializing Switch-Bot platform...
[24.12.2020, 11:24:25] [Switch-Bot] TTL not provided, using default TTL.
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] Discovered Humidifier undefined - undefined
[24.12.2020, 11:24:27] [Switch-Bot] Adding new accessory: undefined undefined Humidifier
[24.12.2020, 11:24:27] A platform configured a new accessory under the plugin name 'homebridge-switch-bot'. However no loaded plugin could be found for the name!
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] A LLC Device has been discovered with a deviceModel that does not start with T5, D6 or T9
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] A LLC Device has been discovered with a deviceModel that does not start with T5, D6 or T9
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] A LLC Device has been discovered with a deviceModel that does not start with T5, D6 or T9
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] A LLC Device has been discovered with a deviceModel that does not start with T5, D6 or T9
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] A LLC Device has been discovered with a deviceModel that does not start with T5, D6 or T9
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] A LLC Device has been discovered with a deviceModel that does not start with T5, D6 or T9
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] A LLC Device has been discovered with a deviceModel that does not start with T5, D6 or T9
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] A LLC Device has been discovered with a deviceModel that does not start with T5, D6 or T9
[24.12.2020, 11:24:27] [Switch-Bot] Total Devices Found: undefined
[24.12.2020, 11:24:27] [Switch-Bot] A LLC Device has been discovered with a deviceModel that does not start with T5, D6 or T9
[24.12.2020, 11:29:28] [Switch-Bot] Humidifier - Failed to update status of Luftbefeuchter "Request failed with status code 403" undefined
[24.12.2020, 11:34:28] [Switch-Bot] Humidifier - Failed to update status of Luftbefeuchter "Request failed with status code 403" undefined
[24.12.2020, 11:39:28] [Switch-Bot] Humidifier - Failed to update status of Luftbefeuchter "Request failed with status code 403" undefined
```

**Comment by donavanbecker** [comment]
@DJay-X Are you using the latest beta?

**Comment by DJay-X** [comment]
I installed it from Config UI previously.
Now I did it manually.

```
sudo npm install -g homebridge-switchbot-openapi@0.1.1-beta.4
+ homebridge-switchbot-openapi@0.1.1-beta.4
updated 1 package in 5.659s
```
Unfortunately now Homebridge is crashing.
I run your plugin in a 2nd-instance and loading there only the plugins I need.
Has the name changed? I load "homebridge-switchbot-openapi"

```
{
    "bridge": {
        "name": "Homebridge-2nd-Instance",
        "username": "AA:12:3B:C4:DE:56",
        "port": 12345,
        "pin": "012-34-567",
        "manufacturer": "homebridge.io"
    },
    "plugins": [
        "homebridge-config-ui-x",
        "homebridge-nest",
        "homebridge-homeconnect",
        "homebridge-messenger",
        "homebridge-multipurpose-kettle",
        "homebridge-apple-tv-remote",
        "homebridge-dummy-garage",
        "homebridge-philips-hue-sync-box",
        "homebridge-tedee",
        "homebridge-broadlink-rm",
        "homebridge-switchbot-openapi"
    ],
```

```
[24.12.2020, 14:40:31] Error: The requested platform 'Switch-Bot' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/homebridge/lib/server.js:271:45
    at Array.forEach (<anonymous>:null:null)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:260:31)
    at Server.start (/usr/local/lib/node_modules/homebridge/lib/server.js:73:35)
    at cli (/usr/local/lib/node_modules/homebridge/lib/cli.js:88:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

[24.12.2020, 14:40:31] Got SIGTERM, shutting down Homebridge...
```

**Comment by DJay-X** [comment]
Found it. The config has changed. From Switch-Bot to SwitchBot ;)

```
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "xxxx",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot"
        }
```

**Comment by donavanbecker** [comment]
Yeah I publish v0.1.0 as a placeholder and for users to test their open tokens. Sorry about that!

**Comment by DJay-X** [comment]
v1.0.0

**Comment by KenExplore** [comment]
Looking forward to using air conditioner / light IR devices in HomeKit!

**Comment by donavanbecker** [comment]
@KenExplore I have added logging for the hubs to the plugin now. I could potentially add air conditioners and light ir devices to HomeKit, but I will need you to get me some info.

First you will need to enable device discovery in the plugin settings on Homebridge UI, Then you will need to get the logs that come from this. It will be yellow and will look like this:
```
{
    "statusCode": 100,
    "body": {
        "deviceList": [
            
        ],
        "infraredRemoteList": [
            {
                "deviceId": "12-1234567891011-12131415",
                "deviceName": "Fan",
                "remoteType": "DIY Fan",
                "hubDeviceId": "A123B45B6C78"
            }
        ]
    },
    "message": "success"
}
```
Once you have this, open up [Feature Request](https://git.io/JL14Z).

**Comment by donavanbecker** [comment]
with `v1.2.3`, I have added support for logging of IR Devices. So I will be closing this issue, any new ir devices that people would like added can be added through a feature request.

**Comment by ynny1625** [comment]
Could you please tell me how to write config.json for switchbot hub?
